config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :orders do 
    post :paymentredirect, on: :member
  end
  devise_for :organizers, :controllers => {:registrations => "organizers/registrations", :sessions => "organizers/sessions"}
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  # devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"} 
  
  resources :organizers
  # devise_scope :user do
  #   get 'users/:id', to: 'users/sessions#show', as: 'user'
  # end
  resources :admins
  resources :tickets
  resources :events
  get 'myevents' => 'events#myevents', as: :myevents
  get 'cart' => 'carts#show', as: :cart
  post 'cart/add_all' => 'carts#add_all', as: :cart_add_all
  delete 'cart/line_item/delete/:id' => 'carts#delete', as: :cart_line_item_delete

  get '/paymentfailed' => 'orders#paymentfailed', :as => 'paymentfailed'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "events#index"
  # draw :user
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
  enum status: [:active, :inactive]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :tickets, through: :line_items

    def total
        total = 0
        self.line_items.each do |line_item|
            total += line_item.quantity * line_item.ticket.price
        end
        total
    end
    
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :organizer
    has_one_attached :image, dependent: :destroy # Active Storage
    has_many :tickets, dependent: :destroy, inverse_of: :event
    accepts_nested_attributes_for :tickets, reject_if: :all_blank, allow_destroy: true

    enum category: {other: 0, entertainment: 1, education: 2, sport: 3}
    enum subcategory: {Running: 0, Football: 1, Rugby: 2, Tennis: 3, Swimming: 4, Other: 5 }

    validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :ticket
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :tickets, through: :line_items

    def generate_checksum
        Rails.logger.info("Generating checksum for order #{id}")
        string = "#{email}|#{name}|#{phone}||#{id}|#{name}|http://localhost:3000/orders/#{id}/paymentredirect|#{total}|be5cd73a-d958-491a-9c37-9078c1b3bb31"
        puts(string)
        checksum_token = "5dc5db2a3e82ae36d0c4bbe374e08df93f4282a3c1287a12cbce40cc7874d98f"
        OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), checksum_token, string)
    end
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        enum status: [:pending, :rejected, :active]

        has_many :events
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :event, inverse_of: :tickets
    validates :name, presence: true
    validates :price, presence: true
    validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        enum role: [:general, :organizer]
        enum status: [:verified, :unverified]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    
    def add_all
        @cart = Cart.find_by(id: params[:cart_id])
        @ticket = Ticket.find_by(id: params[:ticket_id])
        @current_cart = Cart.find_by(id: session[:cart_id])

        Rails.logger.debug "Cart ID: #{@current_cart.id}"

        params[:tickets].each do |_, ticket_params| #
            ticket_id = ticket_params[:id].to_i
            ticket_quantity = ticket_params[:quantity].to_i

            next if ticket_quantity <= 0
            current_line_item = @current_cart.line_items.find_by(ticket_id: ticket_id)
            Rails.logger.debug "Current Line Item Before Save: #{current_line_item.inspect}"
            if current_line_item
                current_line_item.quantity += ticket_quantity
            else
                current_line_item = @current_cart.line_items.build(ticket_id: ticket_id, quantity: ticket_quantity)
                # current_line_item.cart = @current_cart
            end
            current_line_item.save
            Rails.logger.debug "Current Line Item: #{current_line_item.inspect}"
        end
        # Redirect to the cart
        redirect_to cart_path
    end

    def delete
        # Find the line item id
        @line_item = LineItem.find_by(id: params[:id])
        Rails.logger.debug "Line Item ID: #{@line_item.id}"
        @line_item.destroy
        #condition if line item is empty
        if @line_item.cart.line_items.empty?
            @line_item.cart.destroy
            session[:cart_id] = nil
            redirect_to root_path
        else
            redirect_to cart_path
        end
        
    end

        
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admins/edit.html.slim
.container.px-25
  / form to edit an admin
  = simple_form_for(@admin) do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
    br
    .form-inputs
      = f.input :email, input_html: { value: @admin.user.email }, readonly: true
      = f.input :phone, hint: 'Enter phone number without country code'

    .form-actions
      = f.button :submit

    = link_to 'Cancel', admins_path, class: 'btn btn-sm btn-outline-dark'

    

app/views/admins/index.html.slim
//display all users that are admins

.container
  h1 Admins
  table.table.table-hover
    thead
      tr
        th Name
        th Email 
        th Phone Number
        th colspan="2" Action
    tbody
      - @users.each do |user|
        - @admins.each do |admin|
          tr
            td = user.name
            td = user.email
            td = admin.phone
            td = link_to 'Show', admin_path(user)
            td = link_to 'Edit', edit_admin_path(user)
            / td = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/admins/show.html.slim
// show admin details
| Name: #{@user.name}
br
| Email: #{@user.email}
br
| Phone Number: #{@admin.phone}
br
= link_to 'Edit', edit_admin_path(@user)
br
= link_to 'Back', admins_path

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg
  .container-fluid 
    = link_to image_tag("/pics/logo.png", width:'100%' ), root_path, class: "navbar-brand"
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        = link_to "Events", events_path, class: "nav-link"
      // admin, superadmin, member
      - if user_signed_in?
        //admin
        - if current_user.admin?
          ul.navbar-nav.ms-auto.mb-2.mb-lg-0 
            li.nav-item.dropdown 
              a.nav-link.dropdown-toggle type="button"  data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false"
                = current_user.name
              ul.dropdown-menu.dropdown-menu-end
                li = link_to "All Organizers", organizers_path, class: "dropdown-item"
                li = link_to "Edit Account", edit_admin_path(current_user), class: "dropdown-item"
                li
                  hr.dropdown-divider
                li = link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } , class: "dropdown-item"
        //member
        - elsif current_user.member?
          ul.navbar-nav.ms-auto.mb-2.mb-lg-0 
            li.nav-item.dropdown 
              a.nav-link.dropdown-toggle type="button"  data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false"
                = current_user.name
              ul.dropdown-menu.dropdown-menu-end
                li = link_to "Edit Account", edit_user_registration_path, class: "dropdown-item"
                li
                  hr.dropdown-divider
                li = link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } , class: "dropdown-item"
        //superadmin        
        - elsif current_user.superadmin?
          ul.navbar-nav.ms-auto.mb-2.mb-lg-0 
            li.nav-item.dropdown 
              a.nav-link.dropdown-toggle type="button"  data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false"
                = current_user.name
              ul.dropdown-menu.dropdown-menu-end
                li = link_to "All Admins", admins_path, class: "dropdown-item"
                li = link_to "Add Admin", new_user_registration_path, class: "dropdown-item"
                li
                  hr.dropdown-divider
                li = link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } , class: "dropdown-item"
        //no role
        - else
          ul.navbar-nav.ms-auto.mb-2.mb-lg-0 
            li.nav-item 
              = link_to "Login", new_user_session_path, class: "nav-link"
            li.nav-item 
              = link_to "Sign Up", new_user_registration_path, class: "nav-link"
            li.nav-item 
              = link_to "Be an organizer", new_organizer_registration_path, class: "nav-link"
      //organizer        
      - elsif organizer_signed_in?
        ul.navbar-nav.ms-auto.mb-2.mb-lg-0 
          li.nav-item.dropdown 
            a.nav-link.dropdown-toggle type="button"  data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false"
              = current_organizer.email
            ul.dropdown-menu.dropdown-menu-end
              li = link_to "Create Event", new_event_path, class: "dropdown-item"
              li = link_to "My Event", myevents_path, class: "dropdown-item"
              li
                hr.dropdown-divider
              li = link_to "Sign Out", destroy_organizer_session_path, data: { "turbo-method": :delete } , class: "dropdown-item"
      //default
      - else
        ul.navbar-nav.ms-auto.mb-2.mb-lg-0 
          li.nav-item 
            = link_to "Login", new_user_session_path, class: "nav-link"
          li.nav-item 
            = link_to "Sign Up", new_user_registration_path, class: "nav-link"
          li.nav-item 
            = link_to "Be an organizer", new_organizer_registration_path, class: "nav-link"
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Concert</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>