config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :orders do 
    post :paymentredirect, on: :member
  end
  devise_for :organizers, :controllers => {:registrations => "organizers/registrations", :sessions => "organizers/sessions"}
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  # devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"} 
  
  resources :organizers
  # devise_scope :user do
  #   get 'users/:id', to: 'users/sessions#show', as: 'user'
  # end
  resources :admins
  resources :tickets
  resources :events
  get 'myevents' => 'events#myevents', as: :myevents
  get 'cart' => 'carts#show', as: :cart
  post 'cart/add_all' => 'carts#add_all', as: :cart_add_all
  delete 'cart/line_item/delete/:id' => 'carts#delete', as: :cart_line_item_delete

  get '/paymentfailed' => 'orders#paymentfailed', :as => 'paymentfailed'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "events#index"
  # draw :user
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :organizer
    has_one_attached :image, dependent: :destroy # Active Storage
    has_many :tickets, dependent: :destroy, inverse_of: :event
    accepts_nested_attributes_for :tickets, reject_if: :all_blank, allow_destroy: true

    enum category: {other: 0, entertainment: 1, education: 2, sport: 3}
    enum subcategory: {Running: 0, Football: 1, Rugby: 2, Tennis: 3, Swimming: 4, Other: 5 }

    validates :name, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all.with_attached_image
    @pagy, @events = pagy(@events, items: 4)
  end

  # GET /events/1 or /events/1.json
  def show
  end

  def myevents
    @events = current_organizer.events
  end
  

  # GET /events/new
  def new
    @event = current_organizer.events.build
    @event.tickets.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :event_date, :category, :subcategory, :location,:image, :organizer_id, tickets_attributes: [:id, :name,:quantity, :price, :_destroy])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.slim
div id="#{dom_id event}"
  .box
    .row.g-0 
      .col-md-4 
        = image_tag event.image, class: "img-fluid rounded-start", style: "width: 100%; height: auto;"
      br
      .col-md-8.d-flex.align-items-center#event-info
        .card-body
          .h3.card-title 
            = event.name
          .p.strong.card-text
            = event.location
            |  |  
            = event.event_date.strftime("%d %B %Y")
          br
            = event.description

    - if organizer_signed_in?    
      .container
        table class="table table-striped table-hover"
          thead 
            tr 
              th Type 
              th Price 
              th Quantity 
              th colspan="2" 
          tbody 
          - event.tickets.each do |ticket|
            tr 
              td = ticket.name 
              td = number_to_currency(ticket.price) 
              td = ticket.quantity
              td = link_to edit_ticket_path(ticket) do 
                i.bi.bi-pencil-square
              td = link_to ticket_path(ticket), data: {turbo_method: :delete, confirm: "Are you sure?"}, class: "btn btn-sm" do
                i.bi.bi-trash.text-danger


    - else 
      .container
        = form_with(url: cart_add_all_path, method: :post) do |f|
          table class="table table-striped table-hover"
            thead
              tr
                th Type
                th Price
                th Quantity Available
                th Qty
            tbody
            - @event.tickets.each do |ticket| 
              tr
                  td = ticket.name
                  td = number_to_currency(ticket.price)
                  td = ticket.quantity
                  td
                    = f.number_field :tickets, value: 0, min: 0, max: ticket.quantity, name: "tickets[#{ticket.id}][quantity]", class: 'form-control'
                    = f.hidden_field :tickets, value: ticket.id, name: "tickets[#{ticket.id}][id]" 
          = f.submit 'Buy Tickets', class: 'btn btn-primary' 
        br
      

app/views/events/_event_ticket_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">

    <div class="row">
      <div class="col">
        <%= f.label :Ticket_Type %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :Quantity %>
        <%= f.text_field :quantity, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :Price %>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <div class="col">
        <%= f.label :Action %>
        <br>
        <button type="button" data-action="nested-form#remove" class="btn btn-outline-danger">
          <i class="bi bi-trash"></i>
        </button>
      </div>
    </div>

  <%= f.hidden_field :_destroy %>
</div>

app/views/events/_form.html.slim
= simple_form_for @event, data:{controller: "nested-form calculate select", nested_form_target: "nested-form.form", nested_form_wrapper_selector_value: ".nested-form-wrapper"} do |f|
  = f.error_notification
  / = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  - if @event.errors.any?
    .alert.alert-danger
      h4 Alert!
      ul
        - @event.errors.full_messages.each do |msg|
          li = msg


  .form-inputs
    .form-control
      = f.file_field :image, class: "form-control"
      = f.input :name, label: 'Event Name', input_html: {data: {calculate_target: "name"}}
      = f.input :description
      = f.input :event_date, as: :date, html5: true
      .row 
        .col 
          = f.input :category, as: :select, collection: Event.categories.keys, :include_blank => " ", input_html: {data: {select_target: "category", action: "change->select#field"}}
        .col class="subcategory" 
          | Subcategory
          = f.input :subcategory, as: :select, collection: Event.subcategories.keys, input_html: {data: {select_target: "sport"}, style: "margin-top:5px"}, label: false 
          / = f.input :subcategory, as: :select, collection: Event.subcategories.keys, input_html: {data: {select_target: "education"}, hidden: "", style: "margin-top:5px" }, label:false 
      = f.input :location
      =f.input :organizer_id , as: :hidden, input_html: {value: current_organizer.id}

      <h4>Tickets</h4>
      = f.fields_for :tickets do |ticket_fields|
        = render "events/event_ticket_form", f: ticket_fields
      / = link_to_add_association 'Add ticket', f, :tickets, partial: "events/event_ticket_form", class: "btn btn-outline-primary btn-sm"
      / = f.link_to_add "Add ticket", :tickets, partial: "events/event_ticket_form", class: "btn btn-outline-primary btn-sm"

      template data-nested-form-target="template"
        = f.fields_for :tickets, Ticket.new, child_index: 'NEW_RECORD' do |ticket_fields| 
          = render "events/event_ticket_form", f: ticket_fields
      template
        = f.fields_for :tickets do |ticket_fields| 
          = render "events/event_ticket_form", f: ticket_fields 

      div data-nested-form-target="target"
      <p></p>
      button type="button" data-action="nested-form#add" class="btn btn-outline-primary btn-sm" Add more ticket type

    <br><br>

  .form-actions
    = f.button :submit, class: "btn btn-info"

app/views/events/edit.html.slim
.container
  h1 Edit Event
  == render "form", event: @event
br
/ h1 style="text-align:center" Edit event 
/ .container
/   = simple_form_for @event, data:{controller: "nested-form calculate select", nested_form_target: "nested-form.form", nested_form_wrapper_selector_value: ".nested-form-wrapper"} do |f|
/     = f.error_notification
/     = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

/     .form-inputs
/       .form-control
/         = f.file_field :image, class: "form-control"
/         = f.input :name, label: 'Event Name', input_html: {data: {calculate_target: "name"}}
/         = f.input :description
/         = f.input :event_date, as: :date, html5: true
/         .row 
/           .col 
/             = f.input :category, as: :select, collection: Event.categories.keys, :include_blank => " ", input_html: {data: {select_target: "category", action: "change->select#field"}}
/           .col class="subcategory" 
/             | Subcategory
/             = f.input :subcategory, as: :select, collection: Event.subcategories.keys, input_html: {data: {select_target: "sport"}, style: "margin-top:5px"}, label: false 
/             / = f.input :subcategory, as: :select, collection: Event.subcategories.keys, input_html: {data: {select_target: "education"}, hidden: "", style: "margin-top:5px" }, label:false 
/         = f.input :location
/         =f.input :organizer_id , as: :hidden, input_html: {value: current_organizer.id}
/     br
/     .form-actions
/       = f.button :submit, class: "btn btn-info"
/   / br

  / div
  /   => link_to "Show this event", @event
  /   '|
  /   =< link_to "Back to events", events_path

app/views/events/index.html.slim
.container-fluid 
  .row.flex-nowrap 
    .col-auto.col-md-3.col-xl-2.px-sm-2.px-0.bg-light
      .d-flex.flex-column.align-items-center.align-items-sm-start.px-3.pt-2.min-vh-100
        = render 'homes/base'

    .col.py-3
      .container
        .row.row-cols-1.row-cols-md-4.g-2
          - @events.each do |event|
            .col
              .card.h-100
                - if event.image.attached?
                  = image_tag event.image, class: "card-img-top" 
                - else
                  | no image
                .card-body
                  h5.card-title 
                    = link_to event.name, event
                  p.card-text
                    = truncate(event.description, :length =>70)
                  p.card-text.bi.bi-geo-alt-fill
                    |    
                    = event.location 
                .card-footer.bi.bi-calendar-event
                  small.text-muted
                    |    
                    = event.event_date.strftime("%d %B %Y")
      == pagy_nav(@pagy)

      / 

app/views/events/new.html.slim
.container
  h1 Create Event
  == render "form", event: @event
br

app/views/events/show.html.slim
p style="color: green" = notice

.container
  == render @event
  - if organizer_signed_in?
    = link_to edit_event_path(@event), class: "btn btn-primary btn-sm" do
      i.bi.bi-pencil-square
      | &nbsp;
      | Edit event
    | &nbsp;
    = link_to event_path(@event), data: {turbo_method: :delete, confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" do
      i.bi.bi-trash
      | &nbsp;
      | Delete event