config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :orders do 
    post :paymentredirect, on: :member
  end
  devise_for :organizers, :controllers => {:registrations => "organizers/registrations", :sessions => "organizers/sessions"}
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  # devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"} 
  
  resources :organizers
  # devise_scope :user do
  #   get 'users/:id', to: 'users/sessions#show', as: 'user'
  # end
  resources :admins
  resources :tickets
  resources :events
  get 'myevents' => 'events#myevents', as: :myevents
  get 'cart' => 'carts#show', as: :cart
  post 'cart/add_all' => 'carts#add_all', as: :cart_add_all
  delete 'cart/line_item/delete/:id' => 'carts#delete', as: :cart_line_item_delete

  get '/paymentfailed' => 'orders#paymentfailed', :as => 'paymentfailed'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "events#index"
  # draw :user
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def get_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.fetch(:payment, {})
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_failpayment.html.slim
.container
    .text-center
        br
        // image from google
        img(src="https://www.freeiconspng.com/thumbs/error-icon/orange-error-icon-0.png" alt="Ooops!" width="100" height="100")
        br  
        h2 Ooops!
        br
        h5 Unfortunately payment was rejected
        p 
            small 
                | Click button below to try again.
        br
        = link_to "Try again", payment.retry_url, target: "_blank", class: "btn btn-primary"

app/views/payments/_form.html.slim
= simple_form_for(@payment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :payment_id
    = f.input :order_number
    = f.input :payment_method
    = f.input :payment_status
    = f.input :receipt_url
    = f.input :status_url
    = f.input :buyer_email
    = f.input :buyer_name
    = f.input :buyer_phone
    = f.input :transaction_amount
    = f.input :retry_url

  .form-actions
    = f.button :submit

app/views/payments/_payment.html.slim
div id="#{dom_id payment}"
- if payment.payment_status == "true"
  p
    strong Payment:
    =< payment.payment_id
  p
    strong Order no:
    =< payment.order_number
  p
    strong Payment method:
    =< payment.payment_method
  p
    strong Payment status:
    =< payment.payment_status
  p
    strong Receipt url:
    =< payment.receipt_url
  p
    strong Status url:
    =< payment.status_url
  p
    strong Buyer email:
    =< payment.buyer_email
  p
    strong Buyer name:
    =< payment.buyer_name
  p
    strong Buyer phone:
    =< payment.buyer_phone
  p
    strong Payment amount:
    =< payment.transaction_amount
- else
  = render partial: "failpayment", locals: { payment: payment }

app/views/payments/edit.html.slim
h1 Editing payment

== render "form", payment: @payment

br

div
  => link_to "Show this payment", @payment
  '|
  =< link_to "Back to payments", payments_path

app/views/payments/index.html.slim
p style="color: green" = notice

h1 Payments

#payments
  - @payments.each do |payment|
    == render payment
    p
      = link_to "Show this payment", payment

= link_to "New payment", new_payment_path

app/views/payments/new.html.slim
h1 New payment

== render "form", payment: @payment

br

div
  = link_to "Back to payments", payments_path

app/views/payments/show.html.slim
p style="color: green" = notice

== render @payment

/ div
/   => link_to "Edit this payment", edit_payment_path(@payment)
/   '|
/   =< link_to "Back to payments", payments_path

/   = button_to "Destroy this payment", @payment, method: :delete